/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    AccordionContent: typeof import('primevue/accordioncontent')['default']
    AccordionHeader: typeof import('primevue/accordionheader')['default']
    AccordionPanel: typeof import('primevue/accordionpanel')['default']
    AutoComplete: typeof import('primevue/autocomplete')['default']
    BestSellingWidget: typeof import('./src/components/dashboard/BestSellingWidget.vue')['default']
    Button: typeof import('primevue/button')['default']
    ButtonGroup: typeof import('primevue/buttongroup')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    ColorPicker: typeof import('primevue/colorpicker')['default']
    Column: typeof import('primevue/column')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    FeaturesWidget: typeof import('./src/components/landing/FeaturesWidget.vue')['default']
    FloatingConfigurator: typeof import('./src/components/FloatingConfigurator.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    Fluid: typeof import('primevue/fluid')['default']
    FooterWidget: typeof import('./src/components/landing/FooterWidget.vue')['default']
    HeroWidget: typeof import('./src/components/landing/HeroWidget.vue')['default']
    HighlightsWidget: typeof import('./src/components/landing/HighlightsWidget.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Knob: typeof import('primevue/knob')['default']
    Listbox: typeof import('primevue/listbox')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    NotificationsWidget: typeof import('./src/components/dashboard/NotificationsWidget.vue')['default']
    ParameterComponent: typeof import('./src/components/task/ParameterComponent.vue')['default']
    PricingWidget: typeof import('./src/components/landing/PricingWidget.vue')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    Rating: typeof import('primevue/rating')['default']
    RecentSalesWidget: typeof import('./src/components/dashboard/RecentSalesWidget.vue')['default']
    RevenueStreamWidget: typeof import('./src/components/dashboard/RevenueStreamWidget.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Slider: typeof import('primevue/slider')['default']
    SplitButton: typeof import('primevue/splitbutton')['default']
    StatsWidget: typeof import('./src/components/dashboard/StatsWidget.vue')['default']
    TaskCrud: typeof import('./src/components/task/TaskCrud.vue')['default']
    TaskRelations: typeof import('./src/components/task/TaskRelations.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleButton: typeof import('primevue/togglebutton')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
    TopbarWidget: typeof import('./src/components/landing/TopbarWidget.vue')['default']
    TreeSelect: typeof import('primevue/treeselect')['default']
    TreeTable: typeof import('primevue/treetable')['default']
  }
  export interface ComponentCustomProperties {
    StyleClass: typeof import('primevue/styleclass')['default']
  }
}
